#coding: utf-8

Author.create([
  { name: "-" },
  { name: "Anthology" },
  { name: "Barbara Siegel, Scott Siegel" },
  { name: "Brian Thompsen" },
  { name: "Bruce R. Cordell" },
  { name: "Cam Banks" },
  { name: "Carrie A. Bebris" },
  { name: "Chet Williamson" },
  { name: "Chris Pierson" },
  { name: "Christopher Rowe" },
  { name: "Clayton Emery" },
  { name: "Dan Parkinson" },
  { name: "Dave Gross" },
  { name: "Dave Gross, Don Bassingthwaite" },
  { name: "David Cook" },
  { name: "Dixie Lee McKeone" },
  { name: "Don Bassingthwaite" },
  { name: "Don Perrin" },
  { name: "Don Perrin, Margaret Weis" },
  { name: "Douglas Niles" },
  { name: "Douglas W. Clark" },
  { name: "Drew Karpyshyn" },
  { name: "Ed Gentry" },
  { name: "Ed Greenwood" },
  { name: "Ed Greenwood, Troy Denning" },
  { name: "Ed Greenwood, Elaine Cunningham" },
  { name: "Ed Greenwood, Jeff Grubb" },
  { name: "Edo Van Belkom" },
  { name: "Edward Bolme" },
  { name: "Elaine Cunningham" },
  { name: "Ellen Dodge Severson" },
  { name: "Ellen Porath" },
  { name: "Erik Scott de Bie" },
  { name: "Erin M. Evans" },
  { name: "Fergus Ryan" },
  { name: "J.Robert King" },
  { name: "Jak Koke" },
  { name: "Jaleigh Johnson" },
  { name: "James Lowder" },
  { name: "James M. Ward" },
  { name: "James P. Davis" },
  { name: "Jean Rabe" },
  { name: "Jeff Crook" },
  { name: "Jeff Grubb" },
  { name: "Jeff Grubb, Kate Novak" },
  { name: "Jeleigh Johnson" },
  { name: "Jenna Helland" },
  { name: "Jess Lebow" },
  { name: "John Maddox Roberts" },
  { name: "Kameron M. Franklin" },
  { name: "Kate Novak" },
  { name: "Keith Francis Strohm" },
  { name: "Kevin Stein" },
  { name: "Linda P. Baker" },
  { name: "Linda P. Baker, Nancy Varian Berberick" },
  { name: "Lisa Smedman" },
  { name: "Lucien Soulban" },
  { name: "Lynn Abbey" },
  { name: "Margaret Weis" },
  { name: "Margaret Weis, Tracy Hickman" },
  { name: "Margaret Weis, Don Perrin" },
  { name: "Mark Anthony" },
  { name: "Mark Anthony, Ellen Porath" },
  { name: "Mark Sehestedt" },
  { name: "Marsheila Rockwell" },
  { name: "Mary H. Herbert" },
  { name: "Mary Kirchoff" },
  { name: "Mary Kirchoff, Douglas Niles" },
  { name: "Mary Kirchoff, Steve Winter" },
  { name: "Mel Odom" },
  { name: "Michael Williams" },
  { name: "Monte Cook" },
  { name: "Murray J. D. Leeder" },
  { name: "Nancy Varian Berberick" },
  { name: "Nancy Varian Berberick, Jeff Crook" },
  { name: "Paul B. Thompson" },
  { name: "Paul B. Thompson, Tonya C. Cook" },
  { name: "Paul B. Thompson, Tonya R. Carter" },
  { name: "Paul S. Kemp" },
  { name: "Peter Archer" },
  { name: "Philip Athans" },
  { name: "R. A. Salvatore" },
  { name: "Richard A. Knaak" },
  { name: "Richard Baker" },
  { name: "Richard Lee Byers" },
  { name: "Roland J. Green" },
  { name: "Rosemary Jones" },
  { name: "Samantha Henderson" },
  { name: "Scott Ciencin" },
  { name: "Stephen D. Sullivan" },
  { name: "Steven Brown, Mary H. Herbert" },
  { name: "Steven E. Schend" },
  { name: "Thomas M. Reid" },
  { name: "Tim Pratt" },
  { name: "Tina Daniell" },
  { name: "Tina Daniell, Jean Rabe" },
  { name: "Tonya C. Cook, Paul B. Thompson" },
  { name: "Troy Denning" },
  { name: "Victor Milan" },
  { name: "Voronica Whitney-Robinson" }
])

