#coding: utf-8

Series.create([
  { realm_id: 2, name: "-" },
  { realm_id: 2, name: "Anthology" },

  { realm_id: 2, name: "Abolethic Sovereignty" },
  { realm_id: 2, name: "Abyssal Plague" },
  { realm_id: 2, name: "Adventures" },
  { realm_id: 2, name: "Avatar" },
  { realm_id: 2, name: "Baldurs Gate" },
  { realm_id: 2, name: "Blades of the Moonsea" },
  { realm_id: 2, name: "Brotherhood of the Griffon" },
  { realm_id: 2, name: "Chosen of Nendawen" },
  { realm_id: 2, name: "Citadels" },
  { realm_id: 2, name: "Cities" },
  { realm_id: 2, name: "Cleric Quintet" },
  { realm_id: 2, name: "Cormyr Saga" },
  { realm_id: 2, name: "Counselors and Kings" },
  { realm_id: 2, name: "Cycle of Night" },
  { realm_id: 2, name: "Dark Elf Trilogy" },
  { realm_id: 2, name: "Darker Road" },
  { realm_id: 2, name: "Druidhome Trilogy" },
  { realm_id: 2, name: "Dungeons" },
  { realm_id: 2, name: "Elminster" },
  { realm_id: 2, name: "Empyrean Odyssey" },
  { realm_id: 2, name: "Erevis Cale Trilogy" },
  { realm_id: 2, name: "Fighters" },
  { realm_id: 2, name: "Finders Stone Trilogy" },
  { realm_id: 2, name: "Harpers" },
  { realm_id: 2, name: "Haunted Lands" },
  { realm_id: 2, name: "House of Serpents" },
  { realm_id: 2, name: "Hunters Blades Trilogy" },
  { realm_id: 2, name: "Icewind Dale Trilogy" },
  { realm_id: 2, name: "Knights of Myth Drannor" },
  { realm_id: 2, name: "Lady Penitent" },
  { realm_id: 2, name: "Last Mythal" },
  { realm_id: 2, name: "Legacy of the Drow" },
  { realm_id: 2, name: "Lost Empires" },
  { realm_id: 2, name: "Lost Legends" },
  { realm_id: 2, name: "Moonshae Trilogy" },
  { realm_id: 2, name: "Netheril Trilogy" },
  { realm_id: 2, name: "Neverwinter" },
  { realm_id: 2, name: "Nobles Series" },
  { realm_id: 2, name: "Paths of Darkness" },
  { realm_id: 2, name: "Pool of Radiance" },
  { realm_id: 2, name: "Priests" },
  { realm_id: 2, name: "Return of the Archwizards" },
  { realm_id: 2, name: "Rogues" },
  { realm_id: 2, name: "Sage of Shadowdale" },
  { realm_id: 2, name: "Scions of Arrabar Trilogy" },
  { realm_id: 2, name: "Sellswords" },
  { realm_id: 2, name: "Sembia" },
  { realm_id: 2, name: "Seven Sisters" },
  { realm_id: 2, name: "Shadow of the Avatar" },
  { realm_id: 2, name: "Shandrils Saga" },
  { realm_id: 2, name: "Songs & Swords" },
  { realm_id: 2, name: "Starlight and Shadows" },
  { realm_id: 2, name: "Stone of Tymora" },
  { realm_id: 2, name: "Threat from the Sea" },
  { realm_id: 2, name: "Transitions" },
  { realm_id: 2, name: "Twilight Giants" },
  { realm_id: 2, name: "Twilight War" },
  { realm_id: 2, name: "War of the Spider Queen" },
  { realm_id: 2, name: "Watercourse Trilogy" },
  { realm_id: 2, name: "Waterdeep" },
  { realm_id: 2, name: "Wilds" },
  { realm_id: 2, name: "Wizards" },
  { realm_id: 2, name: "Year of Rogue Dragons" },

  { realm_id: 3, name: "-" },
  { realm_id: 3, name: "Anthology" },

  { realm_id: 3, name: "Adventures in Krynn" },
  { realm_id: 3, name: "Age of Mortals" },
  { realm_id: 3, name: "Anvil of Time" },
  { realm_id: 3, name: "Barbarians" },
  { realm_id: 3, name: "Bertrems Guide" },
  { realm_id: 3, name: "Bridges of Time" },
  { realm_id: 3, name: "Champions" },
  { realm_id: 3, name: "Chaos War" },
  { realm_id: 3, name: "Chronicles" },
  { realm_id: 3, name: "Classics" },
  { realm_id: 3, name: "Crossroads" },
  { realm_id: 3, name: "Dark Disciple" },
  { realm_id: 3, name: "Defenders of Magic" },
  { realm_id: 3, name: "Dhamon Saga" },
  { realm_id: 3, name: "Dragonlance Dragons" },
  { realm_id: 3, name: "Dragons from the War of Souls" },
  { realm_id: 3, name: "Dragons of a New Age" },
  { realm_id: 3, name: "Dwarf Home" },
  { realm_id: 3, name: "Dwarven Nations Trilogy" },
  { realm_id: 3, name: "Elven Exiles" },
  { realm_id: 3, name: "Elven Nations Trilogy" },
  { realm_id: 3, name: "Ergoth Trilogy" },
  { realm_id: 3, name: "Heroes" },
  { realm_id: 3, name: "Heroes II" },
  { realm_id: 3, name: "Icewall Trilogy" },
  { realm_id: 3, name: "Kangs Regiment" },
  { realm_id: 3, name: "Kingpriest Trilogy" },
  { realm_id: 3, name: "Legends" },
  { realm_id: 3, name: "Linsha Trilogy" },
  { realm_id: 3, name: "Lost Chronicles" },
  { realm_id: 3, name: "Lost Histories" },
  { realm_id: 3, name: "Lost Legends" },
  { realm_id: 3, name: "Meetings Sextet" },
  { realm_id: 3, name: "Minotaur Wars" },
  { realm_id: 3, name: "Ogre Titans" },
  { realm_id: 3, name: "Preludes" },
  { realm_id: 3, name: "Preludes II" },
  { realm_id: 3, name: "Raistlin Chronicles" },
  { realm_id: 3, name: "Rise of Solamnia" },
  { realm_id: 3, name: "Stonetellers" },
  { realm_id: 3, name: "Tales" },
  { realm_id: 3, name: "Tales II" },
  { realm_id: 3, name: "Tales from the War of Souls" },
  { realm_id: 3, name: "Tales from the World of Krynn" },
  { realm_id: 3, name: "Tales of the Fifth Age" },
  { realm_id: 3, name: "Villains" },
  { realm_id: 3, name: "War of Souls" },
  { realm_id: 3, name: "Warriors" }
])

