#coding: utf-8

Book.create([
  { title: 'Dragons of Autumn Twilight', description: 'Margaret Weis, Tracy Hickman', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of Winter Night', description: 'Margaret Weis, Tracy Hickman', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of Spring Dawning', description: 'Margaret Weis, Tracy Hickman', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Time of the Twins', description: 'Margaret Weis, Tracy Hickman', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'War of the Twins', description: 'Margaret Weis, Tracy Hickman', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Test of the Twins', description: 'Margaret Weis, Tracy Hickman', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of the Dwarven Depths', description: 'Margaret Weis & Tracy Hickman', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of the Highlord Skies', description: 'Margaret Weis & Tracy Hickman', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of the Hourglass Mage', description: 'Margaret Weis, Tracy Hickman', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Magic of Krynn, The', description: 'Anthology', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Kender, Gully Dwarves, and Gnomes', description: 'Anthology', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Love and War', description: 'Anthology', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Reign of Istar, The', description: 'Anthology', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Cataclysm, The', description: 'Anthology', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'War of the Lance, The', description: 'Anthology', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Darkness & Light', description: 'Paul B.Thompson, Tonya R.Carter', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Kendermore', description: 'Mary Kirchoff', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Brothers Majere', description: 'Kevin Stein', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Riverwind the Plainsman', description: 'Paul B. Thompson & Tonya R. Carter', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Flint the King', description: 'Mary Kirchoff & Douglas Niles', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Tanis the Shadow Years', description: 'Barbara Siegel, Scott Siegel', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Legend of Huma, The', description: 'Richard A. Knaak', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Stormblade', description: 'Nancy Varian Berberick', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Weasels Luck', description: 'Michael Williams', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Kaz the Minotaur', description: 'Richard A.Knaak', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Gates of Thorbardin, The', description: 'Dan Parkinson', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Galen Beknighted', description: 'Michael Williams', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Kindred Spirits', description: 'Mark Anthony, Ellen Porath', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Wanderlust', description: 'Mary Kirchoff, Steve Winter', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dark Heart', description: 'Tina Daniell', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Oath and the Measure, The', description: 'Michael Williams', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Steel and Stone', description: 'Ellen Porath', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Companions, The', description: 'Tina Daniell', volume: '6', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Firstborn', description: 'Paul B.Thompson, Tonya C.Cook', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Kinslayer War, The', description: 'Douglas Niles', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Qualinesti, The', description: 'Paul B.Thompson, Tonya C.Cook', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Covenant of the Forge, The', description: 'Dan Parkinson', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Hammer and Axe', description: 'Dan Parkinson', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Swordsheath Scroll, The', description: 'Dan Parkinson', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Night of the Eye', description: 'Mary Kirchoff', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Medusa Plague, The', description: 'Mary Kirchoff', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Seventh Sentinel, The', description: 'Mary Kirchoff', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of a Fallen Sun', description: 'Margaret Weis, Tracy Hickman', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of a Lost Star', description: 'Margaret Weis, Tracy Hickman', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of a Vanished Moon', description: 'Margaret Weis, Tracy Hickman', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Messenger, The', description: 'Douglas Niles', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Golden Orb, The', description: 'Douglas Niles', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Winterheim', description: 'Douglas Niles', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Before the Mask', description: 'Michael Williams', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Black Wing, The', description: 'Mary Kirchoff', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Emperor of Ansalon', description: 'Douglas Niles', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Hederick the Theocrat', description: 'Ellen Dodge Severson', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lord Toede', description: 'Jeff Grubb', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dark Queen, The', description: 'Michael Williams', volume: '6', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Kagonesti, The', description: 'Douglas Niles', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Irda, The', description: 'Linda P.Baker', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dargonesti, The', description: 'Paul B.Thompson, Tonya Cook', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Land of the Minotaurs', description: 'Richard A.Knaak', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Gully Dwarves, The', description: 'Dan Parkinson', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons, The', description: 'Douglas Niles', volume: '6', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Knights of the Crown', description: 'Roland J.Green', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Maquesta Kar-Thon', description: 'Tina Daniell, Jean Rabe', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Knights of the Sword', description: 'Roland, J.Green', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Theros Ironfeld', description: 'Don Perrin', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Knights of the Rose', description: 'Roland J.Green', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lord Soth', description: 'Edo Van Belkom', volume: '6', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Wayward Knights, The', description: 'Roland J.Green', volume: '7', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dawning of a New Age, The', description: 'Jean Rabe', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Day of the Tempest, The', description: 'Jean Rabe', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Eve of the Maelstrom, The', description: 'Jean Rabe', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Downfall', description: 'Jean Rabe', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Betrayal', description: 'Jean Rabe', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Redemption', description: 'Jean Rabe', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Relics and Omens', description: 'Margaret Weis, Tracy Hickman', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Heroes and Fools', description: 'Margared Weis, Tracy Hickman', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Rebels and Tyrants', description: 'Margaret Weis, Tracy Hickman', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Children of the Plains', description: 'Paul B.Thompson, Tonya C.Cook', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Brother of the Dragon', description: 'Paul B.Thompson, Tonya C.Cook', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sister of the Sword', description: 'Paul B.Thompson, Tonya C.Cook', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dalamar the Dark', description: 'Nancy Varian Berberick', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Citadel, The', description: 'Richard A.Knaak', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Murder in Tarsis', description: 'John Maddox Roberts', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Inheritance, The', description: 'Nancy Varian Berberick', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Last Thane, The', description: 'Douglas Niles', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Tears of the Night Sky', description: 'Linda P.Baker, Nancy Varian Berberick', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Puppet King, The', description: 'Douglas Niles', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Reavers of the Blood Sea', description: 'Richard A.Knaak', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Siege of Mt. Nevermind, The', description: 'Fergus Ryan', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Thieves Guild, The', description: 'Jeff Crook', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragon Isles, The', description: 'Stephen D.Sullivan', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Middle of Nowhere, The', description: 'Paul B.Thompson', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons Bluff', description: 'Mary H.Herbert', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Clandestine Circle, The', description: 'Mary H.Herbert', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Rose and the Skull, The', description: 'Jeff Crook', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dezras Quest', description: 'Chris Pierson', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Legacy of Steel', description: 'Mary H.Herbert', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Spirit of the Wind', description: 'Chris Pierson', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Silver Stair, The', description: 'Jean Rabe', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lioness, The', description: 'Nancy Varian Berberick', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dark Thane', description: 'Jeff Crook', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Prisoner of Haven', description: 'Nancy Varian Berberick', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lake of Death, The', description: 'Jean Rabe', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Wizards Conclave', description: 'Douglas Niles', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Conundrum', description: 'Jeff Crook', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Warriors Journey, A', description: 'Paul B.Thompson', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Wizards Fate, The', description: 'Paul B.Thompson, Tonya C.Crook', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Heros Justice, A', description: 'Paul B.Thompson, Tonya C.Cook', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'City of the Lost', description: 'Mary H.Herbert', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Flight of the Fallen', description: 'Mary H.Herbert', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Return of the Exile', description: 'Mary H.Herbert', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Night of Blood', description: 'Richard A.Knaak', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Tides of Blood', description: 'Richard A.Knaak', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Empire of Blood', description: 'Richard A.Knaak', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of Krynn, The', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons at War, The', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of Chaos, The', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Amber and Ashes', description: 'Margaret Weis', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Amber and Iron', description: 'Margaret Weis', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Amber and Blood', description: 'Margaret Weis', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lord of the Rose', description: 'Douglas Niles', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crown and the Sword, The', description: 'Douglas Niles', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Measure and the Truth, The', description: 'Douglas Niles', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sanctuary', description: 'Paul B.Thompson, Tonya C.Cook', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Alliances', description: 'Tonya C.Cook, Paul B.Thompson', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Destiny', description: 'Tonya C.Cook, Paul B.Thompson', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Alien Sea, The', description: 'Lucien Soulban', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Great White Wyrm, The', description: 'Peter Archer', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Protecting Palanthas', description: 'Douglas W.Clark', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Saving Solace', description: 'Douglas W.Clark', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Chosen of the Gods', description: 'Chris Pierson', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Divine Hammer', description: 'Chris Pierson', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sacred Fire', description: 'Chris Pierson', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sellsword, The', description: 'Cam Banks', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Survivors, The', description: '-', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Renegade Wizards', description: 'Lucien Soulban', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Forest King, The', description: 'Paul B.Thompson', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Vinas Solamnus', description: 'J.Robert King', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Fistandantilus Reborn', description: 'Douglas Niles', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Soulforge, The', description: 'Margaret Weis', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Brothers in Arms', description: 'Margaret Weis, Don Perrin', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Doom Brigade, The', description: 'Margaret Weis, Don Perrin', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Draconian Measures', description: 'Don Perrin, Margaret Weis', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Black Talon, The', description: 'Richard A.Knaak', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Fire Rose, The', description: 'Richard A.Knaak', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Gargoyle King, The', description: 'Richard A.Knaak', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Secret of Pax Tharkas, The', description: 'Douglas Niles', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Heir of Kayolin, The', description: 'Douglas Niles', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Fate of Thorbardin, The', description: 'Douglas Niles', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Bertrems Guide to the War of Souls vol.1', description: 'Nacy Varian Berberick, Jeff Crook', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Bertrems Guide to the War of Souls vol.2', description: 'Steven Brown, Mary H.Herbert', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Bertrems Guide to the Age of Mortals', description: 'Nancy Varian Berberick', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Rebellion, The', description: 'Jean Rabe', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Death March', description: 'Jean Rabe', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Goblin Nation', description: 'Jean Rabe', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Players of Gilean, The', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Search for Magic, The', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Search for Power, The', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Tales of Uncle Trapspringer', description: 'Dixie Lee McKeone', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of Summer Flame', description: 'Margaret Weis, Tracy Hickman', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Second Generation, The', description: 'Margaret Weis', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Odyssey of Gilthanas', description: 'Douglas Niles', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Best of Tales, The, vol.1', description: 'Anthology', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Best of Tales, The, vol.2', description: 'Anthology', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons of Time', description: 'Margaret Weis, Tracy Hickman', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dragons in the Archives', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadows of Doom', description: 'Ed Greenwood', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Cloak of Shadows', description: 'Ed Greenwood', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'All Shadows Fled', description: 'Ed Greenwood', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadowdale', description: 'Scott Ciencin', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Tantras', description: 'Scott Ciencin', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Waterdeep', description: 'Troy Denning', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Prince of Lies', description: 'James Lowder', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crucible: The Trial of Cyric the Mad', description: 'Troy Denning', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crucible: The Trial of Cyric the Mad(2)', description: 'Troy Denning', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Darkwalker on Moonshae', description: 'Douglas Niles', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Black Wizards', description: 'Douglas Niles', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Darkwell', description: 'Douglas Niles', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Prophet of Moonshae', description: 'Douglas Niles', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Coral Kingdom', description: 'Douglas Niles', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Druid Queen', description: 'Douglas Niles', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crystal Shard', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Streams of Silver', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Halflings Gem', description: 'R.A.Salvatore', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Homeland', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Exile', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sojourn', description: 'R.A.Salvatore', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Azure Bonds', description: 'Kate Novak', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Wyverns Spur, The', description: 'Kate Novak', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Song of the Saurials', description: 'Kate Novak', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'King Pinch', description: 'David Cook', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'War in Tethyr', description: 'Victor Milan', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Escape from Undermountain', description: 'Mark Anthony', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Mage in the Iron Mask, The', description: 'Brian Thompsen', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Council of Blade, The', description: '-', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Simbles Gift, The', description: 'Lynn Abbey', volume: '6', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sword Play', description: 'Clayton Emery', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dangerous Games', description: 'Clayton Emery', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Mortal Consequences', description: 'Clayton Emery', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Legacy, The', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Starless Night', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Siege of Darkness', description: 'R.A.Salvatore', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Passage to Dawn', description: 'R.A.Salvatore', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Thousand Orcs, The', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lone Drow, The', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Two Swords, The', description: 'R.A.Salvatore', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Canticle', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'In Sylvan Shadows', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Night Masks', description: 'R.A.Salvatore', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Fallen Fortress, The', description: 'R.A.Salvatore', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Chaos Curse, The', description: 'R.A.Salvatore', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Elminster: the Making of a Mage', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Elminster in Myth Drannor', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Temptation of Elminster, The', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Elminster in Hell', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Elminsters Daughter', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Elfshadow', description: 'Elaine Cunningham', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Elfsong', description: 'Elaine Cunningham', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Silver Shadows', description: 'Elaine Cunningham', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Thornhold', description: 'Elaine Cunningham', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dream Spheres, The', description: 'Elaine Cunningham', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Parched Sea, The', description: 'Troy Denning', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Red Magic', description: 'Jean Rabe', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Night Parade, The', description: 'Scott Ciencin', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Ring of Winter, The', description: 'James Lowder', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crypt of the Shadowking', description: 'Mark Anthony', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Soldiers of Ice', description: 'David Cook', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Masquerades', description: 'Kate Novak', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Curse of the Shadowmage', description: 'Mark Anthony', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Veiled Dragon, The', description: 'Troy Denning', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lost Library of Cormanthyr, The', description: 'Mel Odom', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Faces of Deception', description: 'Troy Denning', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Star of Cursrah', description: 'Clayton Emery', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Nether Scroll, The', description: 'Lynn Abbey', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Spellfire', description: 'Ed Greenwood', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crown of Fire', description: 'Ed Greenwood', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Hand of Fire', description: 'Ed Greenwood', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Rising Tide', description: 'Mel Odom', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Under Fallen Stars', description: 'Mel Odom', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sea Devils Eye, The', description: 'Mel Odom', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of the Deep', description: 'Anthology', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Magehound, The', description: 'Elaine Cunningham', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Floodgate, The', description: 'Elaine Cunningham', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Wizardwar, The', description: 'Elaine Cunningham', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Summoning, The', description: 'Troy Denning', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Siege, The', description: 'Troy Denning', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sorcerer, The', description: 'Troy Denning', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of Shadow', description: 'Anthology', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Silent Blade, The', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Spine of the World, The', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Servant of the Shard', description: 'R.A.Salvatore', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sea of Swords', description: 'R.A.Salvatore', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'City of Ravens, The', description: 'Richard Baker', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Temple Hill', description: 'Drew Karpyshyn', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Jewel of Turmish, The', description: 'Mel Odom', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'City of Splendors: A Waterdeep Novel, The', description: 'Ed Greenwood, Elaine Cunningham', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Pool of Radiance', description: 'James M.Ward', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Pools of Darkness', description: 'James M.Ward', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Pool of Twilight', description: 'James M.Ward', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Pool of Radiance: Ruins of Myth Drannor', description: 'Carrie A.Bebris', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Twilight Falling', description: 'Paul S.Kemp', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dawn of Night', description: 'Paul S.Kemp', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Midnights Mask', description: 'Paul S.Kemp', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dissolution', description: 'Richard Lee Byers', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Insurrection', description: 'Thomas M.Reid', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Condemnation', description: 'Richard Baker', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Extinction', description: 'Lisa Smedman', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Annihilation', description: 'Philip Athans', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Resurrection', description: 'Paul S.Kemp', volume: '6', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Alabaster Staff, The', description: 'Edward Bolme', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crimson Gold, The', description: 'Voronica Whitney-Robinson', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Black Bouquet, The', description: 'Richard Lee Byers', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Yellow Silk, The', description: 'Don Bassingthwaite', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Halls of Stormweather, The', description: 'Anthology', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadows Witness', description: 'Paul S.Kemp', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shattered Mask, The', description: 'Richard Lee Byers', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Black Wolf', description: 'Dave Gross', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Heirs of Prophecy', description: 'Lisa Smedman', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sands of the Soul', description: 'Voronica Whitney-Robinson', volume: '6', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lord of Stormweather', description: 'Dave Gross', volume: '7', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Cormyr: A Novel', description: 'Ed Greenwood, Jeff Grubb', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Beyond the High Road', description: 'Troy Denning', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Death of the Dragon', description: 'Ed Greenwood and Troy Denning', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sapphire Crescent, The', description: 'Thomas M.Reid', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Ruby Guardian, The', description: 'Thomas M.Reid', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Emerald Sceptre, The', description: 'Thomas M.Reid', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Forsaken House', description: 'Richard Baker', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Farthest Reach', description: 'Richard Baker', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Final Gate', description: 'Richard Baker', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of the Elves', description: 'Anthology', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lady of Poison', description: 'Bruce R.Cordell', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Mistress of the Night', description: 'Dave Gross, Don Bassingthwaite', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Maiden of Pain', description: 'Kameron M.Franklin', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Queen of the Depths', description: 'Richard Lee Byers', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Rage, The', description: 'Richard Lee Byers', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Rite, The', description: 'Richard Lee Byers', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Ruin, The', description: 'Richard Lee Byers', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of the Dragons', description: 'Anthology', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of the Dragons II', description: 'Anthology', volume: '5', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Unholy', description: 'Richard Lee Byers', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Undead', description: 'Richard Lee Byers', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Unclean', description: 'Richard Lee Byers', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of the Dead', description: 'Anthology', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Once Around the Realms', description: 'Brian Thomsen', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of Infamy', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of Valor', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of the Underdark', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of Magic', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of Mystery', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of the Arcane', description: 'Anthology', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Best of the Realms vol.1, The', description: 'Anthology', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Best of the Realms vol.2, The', description: 'Anthology', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Best of the Realms vol.3, The', description: 'Anthology', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Ogres Pact, The', description: 'Troy Denning', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Giant Among Us, The', description: 'Troy Denning', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Titan of Twilight, The', description: 'Troy Denning', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Blackstaff', description: 'Steven E.Schend', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Bloodwalk', description: 'James P.Davis', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Frostfell', description: 'Mark Sehestedt', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Darkvision', description: 'Bruce R.Cordell', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Bladesinger', description: 'Keith Francis Strohm', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Ghostwalker', description: 'Erik Scott de Bie', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Master of Chains', description: 'Jess Lebow', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Son of Thunder', description: 'Murray J.D.Leeder', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Whisper of Waves', description: 'Philip Athans', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Lies of Light', description: 'Philip Athans', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Scream of Stone', description: 'Philip Athans', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Servant of the Shard(2)', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Promise of the Witch-King', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Road to the Patriarch', description: 'R.A.Salvatore', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Swords of Eveningstar', description: 'Ed Greenwood', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Swords of Dragonfire', description: 'Ed Greenwood', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sword Never Sleeps, The', description: 'Ed Greenwood', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Depths of Madness', description: 'Erik Scott de Bie', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crypt of the Moaning Diamond', description: 'Rosemary Jones', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Howling Delve, The', description: 'Jeleigh Johnson', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Stardeep', description: 'Bruce R.Cordell', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadowbred', description: 'Paul S.Kemp', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadowstorm', description: 'Paul S.Kemp', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadowrealm', description: 'Paul S.Kemp', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Realms of War', description: 'Anthology', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sacrifice of the Widow', description: 'Lisa Smedman', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Storm of the Dead', description: 'Lisa Smedman', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Ascendancy of the Last', description: 'Lisa Smedman', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Fractured Sky, The', description: 'Thomas M. Reid', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Gossamer Plain, The', description: 'Thomas M.Reid', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Crystal Mountain, The', description: 'Thomas M.Reid', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Stowaway, The', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadowmask, The', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sentinels, The', description: '-', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: "Finder's Bane", description: 'Jeff Grubb, Kate Novak', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Tymoras Luck', description: 'Jeff Grubb, Kate Novak', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Daughter of the Drow', description: 'Elaine Cunningham', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Tangled Webs', description: 'Elaine Cunningham', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Windwalker', description: 'Elaine Cunningham', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Baldurs Gate', description: 'Philip Athans', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Baldurs Gate II: Shadows of Amn', description: 'Philip Athans', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Baldurs Gate II: Thron of Bhaal', description: 'Drew Karpyshyn', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Stormlight', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Silverfall: Stories of the Seven Sisters', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Venoms Taste', description: 'Lisa Smedman', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Vipers Kiss', description: 'Lisa Smedman', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Vanitys Blood', description: 'Lisa Smedman', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Neversfall', description: 'Ed Gentry', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Obsidian Ridge', description: 'Jess Lebow', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shield of Weeping Ghosts, The', description: 'James P.Davis', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sentinelspire', description: 'Mark Sehestedt', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Orc King, The', description: 'R.A.Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Prirate King, The', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Ghost King, The', description: 'R.A.Salvatore', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Blackstaff Tower', description: 'Steven E.Schend', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Mistshore', description: 'Jeleigh Johnson', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Downshadow', description: 'Erik Scott de Bie', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'City of the Dead', description: 'Rosemary Jones', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'God Catcher, The', description: 'Erin M.Evans', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Circle of Skulls', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Swordmage', description: 'Richard Baker', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Corsair', description: 'Richard Baker', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Avenger', description: 'Richard Baker', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Fanged Crown, The', description: 'Jenna Helland', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Restless Shore, The', description: 'James P.Davis', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Edge of Chaos, The', description: 'Jak Koke', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Wrath of the Blue Lady', description: 'Mel Odom', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Plague of Spells', description: 'Bruce Cordell', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'City of Torment', description: 'Bruce Cordell', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Key of Stars', description: '-', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Hand of the Hunter, The', description: 'Mark Sehestedt', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Cry of the Ghost Wolves, The', description: '-', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Fall of Highwatch, The', description: 'Mark Sehestedt', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Godborn', description: '-', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Godbound', description: '-', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Godslayer', description: '-', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Captive Flame, The', description: 'Richard Lee Byers', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Whisper of Venom', description: 'Richard Lee Byers', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Spectral Blaze, The', description: 'Richard Lee Byers', volume: '3', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Masked Witches, The', description: 'Richard Lee Byers', volume: '4', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Gauntlgrym', description: 'R.A. Salvatore', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Neverwinter', description: 'R.A.Salvatore', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Bury Elminster Deep', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Elminster Must Die', description: 'Ed Greenwood', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadowbane', description: 'Erik Scott de Bie', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sword of the Gods', description: 'Bruce Cordell', volume: '2', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Glass Prison, The', description: 'Monte Cook', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Evermeet: Island of Elves', description: 'Elaine Cunningham', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shadow Stone, The', description: 'Richard Baker', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Murder in Cormyr', description: 'Chet Williamson', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Unbroken Chain', description: 'Jaleigh Johnson', volume: '1', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Sandstorm', description: 'Christopher Rowe', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Dawnbringer', description: 'Samantha Henderson', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Shard Axe, The', description: 'Marsheila Rockwell', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Brimstone Angels', description: 'Erin M. Evans', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Venom in Her Veins', description: 'Tim Pratt', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Brimstone Angels: Lesser Evils', description: 'Erin M. Evans', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Elminster Enraged', description: '-', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Prophet of the Dead', description: '-', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 },
  { title: 'Charons Claw', description: '-', volume: '-', publisher_id:1, status_id:1, series_id:1, author_id:1 }
])

